"""
reports/report_generator.py
━━━━━━━━━━━━━━━━━━━━━━━━━━━
Saves trend analysis + specials to:
  • JSON file (machine-readable)
  • TXT file  (human-readable report)
  • CSV file  (dishes table for Excel/Sheets)
"""

import json
import csv
import os
from datetime import datetime
from pathlib import Path

REPORTS_DIR = Path(__file__).parent / "output"
REPORTS_DIR.mkdir(exist_ok=True)


def save_json(data: dict, city: str) -> str:
    """Save full pipeline output as JSON."""
    slug = city.split(",")[0].strip().lower().replace(" ", "_")
    ts   = datetime.now().strftime("%Y%m%d_%H%M")
    path = REPORTS_DIR / f"{slug}_{ts}_full.json"
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"  💾 JSON saved: {path}")
    return str(path)


def save_txt_report(report_text: str, city: str, specials: dict) -> str:
    """Save human-readable weekly report as TXT."""
    slug = city.split(",")[0].strip().lower().replace(" ", "_")
    ts   = datetime.now().strftime("%Y%m%d_%H%M")
    path = REPORTS_DIR / f"{slug}_{ts}_report.txt"

    header = f"""
{'═'*65}
  🇮🇳  INDIA FOOD TREND AGENT — WEEKLY REPORT
  City: {city}
  Generated: {datetime.now().strftime('%A, %d %B %Y at %I:%M %p')}
{'═'*65}

"""
    # Top ingredients
    top_ings = specials.get("top_weekend_ingredients", [])
    ing_section = "\nTOP WEEKEND INGREDIENTS:\n"
    for i, ing in enumerate(top_ings, 1):
        ing_section += f"  {i}. {ing}\n"

    # Dishes table
    dishes = specials.get("weekend_specials", [])
    dish_section = "\n\nWEEKEND SPECIALS:\n" + "─"*60 + "\n"
    for i, d in enumerate(dishes, 1):
        dish_section += f"""
{i}. {d.get('dish_name','').upper()}
   Category    : {d.get('category','')}
   Price       : {d.get('suggested_price_range','')}
   Demand      : {d.get('predicted_demand','')}
   Food Cost   : {d.get('food_cost_level','')} ({d.get('estimated_food_cost_inr','')})
   Margin      : {d.get('gross_margin_pct','')}
   Inspired By : {d.get('inspired_by','')}
   Key Ingred. : {d.get('key_trending_ingredient','')}
   Best Served : {d.get('best_served','')}

   Description:
   {d.get('description','')}

   Plating Tip:
   {d.get('plating_tip','')}

   Reels Tip:
   {d.get('reels_tip','')}

   Why It'll Trend:
   {d.get('why_it_will_trend','')}
{"─"*60}"""

    strategic = f"\n\nSTRATEGIC INSIGHT:\n{specials.get('strategic_insight','')}\n"
    revenue   = f"\nREVENUE PROJECTION:\n{specials.get('revenue_projection','')}\n"
    footer    = f"\n{'═'*65}\nGenerated by 🇮🇳 India Food Trend Agent · Python + Claude AI\n{'═'*65}\n"

    full = header + ing_section + "\n\n" + report_text + dish_section + strategic + revenue + footer

    with open(path, "w", encoding="utf-8") as f:
        f.write(full)
    print(f"  📄 TXT report saved: {path}")
    return str(path)


def save_csv(specials: dict, city: str) -> str:
    """Save dishes as CSV (opens in Excel / Google Sheets)."""
    slug = city.split(",")[0].strip().lower().replace(" ", "_")
    ts   = datetime.now().strftime("%Y%m%d_%H%M")
    path = REPORTS_DIR / f"{slug}_{ts}_dishes.csv"

    dishes = specials.get("weekend_specials", [])
    if not dishes:
        return ""

    fieldnames = [
        "dish_name", "category", "key_trending_ingredient", "inspired_by",
        "description", "suggested_price_range", "estimated_food_cost_inr",
        "gross_margin_pct", "food_cost_level", "predicted_demand",
        "prep_time_mins", "best_served", "plating_tip", "reels_tip",
        "why_it_will_trend",
    ]

    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(dishes)

    print(f"  📊 CSV saved: {path}")
    return str(path)


def save_all(pipeline_output: dict) -> dict:
    """Save all report formats and return file paths."""
    city     = pipeline_output.get("city", "India")
    specials = pipeline_output.get("specials", {})
    report   = pipeline_output.get("weekly_report", "")

    print(f"\n📁 Saving reports for {city}...")
    paths = {
        "json": save_json(pipeline_output, city),
        "txt":  save_txt_report(report, city, specials),
        "csv":  save_csv(specials, city),
    }
    print(f"  ✅ All reports saved to: {REPORTS_DIR}")
    return paths
